### ISSUE TITLE
Can't work out the in-place evaluation

### ISSUE THREAD

**Issue by elken** [radian-software/apheleia#106]
So I have shfmt set to

```llisp
(shfmt
  ("shfmt" "-ci"
   (unless indent-tabs-mode
     (list "-i"
           (number-to-string tab-width)))
   "-ln"
   (pcase sh-shell
     (`bash "bash")
     (`mksh "mksh")
     (_ "posix"))))
```

Which according to the README should "evaluate in place", has this functionality changed? I'm setting it through a macro currently but it's setting it as a list.

**Comment by raxod502** [comment]
Seems to work for me. I evaluated this elisp:

```elisp
(setf (alist-get 'shfmt-modified apheleia-formatters)
        '("shfmt" "-ci"
          (unless indent-tabs-mode
            (list "-i"
                  (number-to-string tab-width)))
          "-ln"
          (pcase sh-shell
            (`bash "bash")
            (`mksh "mksh")
            (_ "posix"))))
```

Then `(setq apheleia-log-only-errors nil)`, went to a bash script, `C-u M-x apheleia-format-buffer RET shfmt-modified RET`, and saw the following expected output in `*apheleia-shfmt-log*`:

```
Mon Jun 20 14:15:44 2022 :: /home/raxod502/files/code/shell/pass-ln/packaging/
$ shfmt -ci -i 8 -ln bash

(no output on stderr)

Command succeeded with exit code 0.
```

Are you seeing something different?

**Comment by elken** [comment]
You're right! Seems it's an issue with the macro. PEBCAK!
