### ISSUE TITLE
clang-format fails to determine main header

### ISSUE THREAD

**Issue by ItsHoff** [radian-software/apheleia#108]
With the following `_clang-format`

```
SortIncludes: true
IncludeBlocks: Regroup
```
`clang-format -i sort_includes.cpp` formats the following `sort_includes.cpp`:
```
#include "other_include.hpp"
#include <vector>
#include "sort_includes.hpp"
```
into 
```
#include "sort_includes.hpp"

#include "other_include.hpp"

#include <vector>
```
However, running `aphelia-format-buffer` produces file with
```
#include "other_include.hpp"
#include "sort_includes.hpp"

#include <vector>
```
It seems that when apheleia runs `clang-format`, `clang-format` cannot determine the main header (see, https://clang.llvm.org/docs/ClangFormatStyleOptions.html IncludeCategories). I'm guessing this occurs because apheleia send the file to `clang-format` via standard input and for that reason `clang-format` does not know the filename. 

I was able to workaround the issue if I modified the `clang-format` entry in `apheleia-formatters` to `'("clang-format" file)`. `clang-format` also seems to have a command line option `--assume-filename=<string>`, which could also solve the issue.

**Comment by lassik** [comment]
Format-all uses `-assume-filename`. Try if that fixes it.

**Comment by ItsHoff** [comment]
> Format-all uses `-assume-filename`. Try if that fixes it.

The [format-all](https://github.com/lassik/emacs-format-all-the-code) package seems to handle this correctly.

**Comment by elken** [comment]
@ItsHoff Try the linked PR :)
