### ISSUE TITLE
How can I turn off apheleia-mode for Latex-mode?

### ISSUE THREAD

**Issue by avatar-lavventura** [radian-software/apheleia#113]
I want to disable `apheleia-mode` for the `Latex-mode`. I have tried following solution but it did not help.

What I tried, which did not help:

```lisp
(apheleia-global-mode +1)
(defun app/LaTeX-mode-hook ()
  (apheleia-global-mode -1))
(add-hook 'LaTeX-mode-hook 'app/LaTeX-mode-hook)
```

Is there any way to disable `apheleia` for a major mode like `LaTeX-mode`?

**Comment by avatar-lavventura** [comment]
I have solved it using https://emacs.stackexchange.com/a/72882/18414:


>```lisp
>(defun app/LaTeX-mode-hook ()
>  (apheleia-mode -1))
>(add-hook 'LaTeX-mode-hook 'app/LaTeX-mode-hook)
>```

**Comment by raxod502** [comment]
Yeah, you need to disable the local mode, not the global one.
