### ISSUE TITLE
Prettier is broken

### ISSUE THREAD

**Issue by artemkovalyov** [radian-software/apheleia#117]
I don't get what `--stdin-filepath` argument doing there. It's needless and in fact, breaks linting. After fixing my formatters list locally like this `(add-to-list 'apheleia-formatters '(prettier . (npx "prettier" filepath)))` it perfectly worked. We are providing file path anyways and the output is printed to "stdout" as expected.
https://prettier.io/docs/en/cli.html#--stdin-filepath

`(prettier . (npx "prettier" "--stdin-filepath" filepath))`
https://github.com/radian-software/apheleia/blob/0c5e40e8bc0e837b778452b3f061ff85e39a967a/apheleia.el#L933

**Comment by billop** [comment]
Here is why that was added:
https://github.com/radian-software/apheleia/issues/21
https://github.com/radian-software/apheleia/commit/3be4b486dc09df375fe359e3c5a933c53252a146

**Comment by anonimitoraf** [comment]
Weird, I also have this problem. @artemkovalyov did you just patch it to `(add-to-list 'apheleia-formatters '(prettier . (npx "prettier" filepath)))`?
