### ISSUE TITLE
[Solved] Standard Prettier config fails, how to debug it? Logs are insufficient. Can't figure out what causes the exit code 1.

### ISSUE THREAD

**Issue by artemkovalyov** [radian-software/apheleia#118]
The default `prettier` config doesn't work for me. It always returns with an error about the exit code:

```
Wed Aug 17 17:39:39 2022 :: /umetra/test/my-app/src/
$ /umetra/test/my-app/node_modules/.bin/prettier --stdin-filepath /umetra/test/my-app/src/hooks.ts

(no output on stderr)

Command failed with exit code 1.
```

I tried to change it by providing a parser and removing the guesswork, still doesn't work.

```
Wed Aug 17 17:34:05 2022 :: /umetra/test/my-app/src/
$ /umetra/test/my-app/node_modules/.bin/prettier --parser\=typescript

(no output on stderr)

Command failed with exit code 1.
```

From the command line, it works fine with any of the options above if I provide the file from STDIN like this:
`cat src/hooks.ts | npx prettier --parser=typescript`

It also works fine when I provide a `parser` and `filepath`. But in this case, it adds some gibberish coming from the STDOUT:
```ts
hooks.ts[2K[1Gimport cookie from 'cookie';
import { v4 as uuid } from '@lukeed/uuid';
import type { Handle } from '@sveltejs/kit';
```

I'm lost about debugging what causes Aphelia to see an exit code of 1 while it works on the command line. There's a feeling that STDIN is not there for some reason, it's the only case how I managed to reproduce an exit code. What I can do from here to make it work again?

**Comment by artemkovalyov** [comment]
Even after activating logging it works and gives results only when I provide a filepath to the command:
```
 Wed Aug 17 17:53:09 2022 :: /umetra/test/my-app/src/
$ /umetra/test/my-app/node_modules/.bin/prettier --parser\=typescript /umetra/test/my-app/src/hooks.ts

[error] hooks.ts: SyntaxError: Invalid character. (1:9)
[error] > 1 | hooks.ts[2K[1Gimport cookie from 'cookie';
[error]     |         ^
[error]   2 | import { v4 as uuid } from '@lukeed/uuid';
[error]   3 | import type { Handle } from '@sveltejs/kit';
[error]   4 |

Command failed with exit code 2.
```

If I don't provide filepath then no helpful output is provided. This same command works well in the console.
```
Wed Aug 17 17:54:16 2022 :: /umetra/test/my-app/src/
$ /umetra/test/my-app/node_modules/.bin/prettier --parser\=typescript

(no output on stderr)

Command failed with exit code 1.
```

**Comment by artemkovalyov** [comment]
Raised logLevel to debug, not much help
```
Wed Aug 17 18:00:39 2022 :: /umetra/test/my-app/src/
$ /umetra/test/my-app/node_modules/.bin/prettier --parser\=typescript --loglevel\=debug

[debug] normalized argv: {"_":[],"cache":false,"color":true,"editorconfig":true,"parser":"typescript","loglevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":".prettierignore","plugins":[],"pluginSearchDirs":[],"__raw":{"_":[],"cache":false,"color":true,"editorconfig":true,"parser":"typescript","loglevel":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}}

Command failed with exit code 1.
```

**Comment by artemkovalyov** [comment]
I went on a debugging journey and can't understand how tests for `prettier` can still pass. The tool simply doesn't wait for STDIN and fails immediately with an error that should completely break the default setup in aphelia.

It works fine with Linux pipe but not with Emacs' way of providing STDIN after the process was created. It manages to fail in between. There's a ray of hope it can be solved by this: https://github.com/prettier/prettier/issues/13271

As a workaround, I created this simple script that waits for STDIN properly and pipes it to prettier the Linux way so that it doesn't fail because of no args.

```sh
#!/bin/bash

cat | prettier  --plugin-search-dir=. --stdin-filepath $1
```

Then I just plug it into Aphelia like this:

```lisp
(setf (alist-get 'prettier apheleia-formatters)
      '("/home/artem/art.sh" filepath))
```
It works like a charm. I also had to create another formatter for Svelte base on prettier where I also provide a parser for the plugin.

I really hope Prettier CLI is improved and such ugly things wouldn't be required. There's a feeling like I overlooked something obvious but I didn't find another way to make it work.

**Comment by raxod502** [comment]
If I understand correctly, https://github.com/radian-software/apheleia/pull/119 should fix this. Does that sound right?
