### ISSUE TITLE
add check for narrowed buffer 

### ISSUE THREAD

**Issue by tpeacock19** [radian-software/apheleia#124]
With the recent commit to add elisp formatting I've run into an issue where apheleia is deleting all text from narrowed buffers. I understand that support for narrowed buffers [isnt currently implemented](https://github.com/radian-software/apheleia/issues/43), so perhaps it would be a good idea to check if the buffer is narrowed and prevent apheleia from making any changes. Since this is just one line I'll just leave a working diff here

```diff
1 file changed, 1 insertion(+), 1 deletion(-)
apheleia.el | 2 +-

modified   apheleia.el
@@ -1285,7 +1285,7 @@ operating, to prevent an infinite loop.")
 (defun apheleia--format-after-save ()
   "Run code formatter for current buffer if any configured, then save."
   (unless apheleia--format-after-save-in-progress
-    (when apheleia-mode
+    (when (and apheleia-mode (not (buffer-narrowed-p)))
       (when-let ((formatters (apheleia--get-formatters)))
         (apheleia-format-buffer
          formatters

```

**Comment by elken** [comment]
In future please feel free to submit pull requests yourself :D
