### ISSUE TITLE
Conditionally disable apheleia-mode locally

### ISSUE THREAD

**Issue by daanturo** [radian-software/apheleia#134]
When working in shared code base, auto-formatting may lead to diff
noise disasters when there isn't a commonly agreed code formatting
convention (or worse: people don't even care).

With `apheleia-global-mode` enabled, I think we should add an option
to conditionally disable auto-formatting that is ran at every save,
but still not get in the way when we want to call
`apheleia-format-buffer` explicitly.

While still using `apheleia-global-mode`, adding a "dummy" formatter
to `apheleia-formatters` (like `#'ignore`), and set
`apheleia-formatter` to it `.dir-locals-2.el` may disable
auto-formatting, but it prevents us from `M-x apheleia-format-buffer`.

**Comment by raxod502** [comment]
Yeah, this is actually a pain point for me as well, but I have never gotten around to fixing it. I think your implementation makes sense. I have silly things like this in my config:

```elisp
(radian-defhook radian-local--disable-apheleia-for-riju-yaml ()
  find-file-hook
  "Disable Apheleia reformatting for Riju YAML files."
  (when (and buffer-file-name
             (string-match-p
              "\\`/home/raxod502/files/code/web/riju/[^.]+\\.yaml\\'"
              buffer-file-name))
    (apheleia-mode -1)))
```
