### ISSUE TITLE
Add formatter for `Caddyfile`

### ISSUE THREAD

**Issue by rassie** [radian-software/apheleia#136]
It would be nice to have a `Caddyfile` formatter support. It is included in `caddy` itself.

To format `stdin` to `stdout`: 
```
$ caddy fmt -
```

`caddy` itself can be fetched from Github Releases, e.g. [2.6.1 Linux AMD64 tar archive](https://github.com/caddyserver/caddy/releases/download/v2.6.1/caddy_2.6.1_linux_amd64.tar.gz), which directly includes the `caddy` binary.

**Comment by elken** [comment]
You're more than welcome to review the [guide](https://github.com/radian-software/apheleia#contributing) and submit your own :)

**Comment by rassie** [comment]
I can surely try :) My problem is that I'm not a user of apheleia yet, I'm patiently waiting for doom-emacs integration, but I can still submit a PR.
