### ISSUE TITLE
Formatters using `npx` yield errors during tests

### ISSUE THREAD

**Issue by jaybarra** [radian-software/apheleia#163]
Tests using prettier will fail during the `make fmt-test FORMATTERS=prettier*` step.
This affects all of the `prettier-*` formatters. Found during #162 

Steps to reproduce:
Follow steps for [adding a formatter](https://github.com/radian-software/apheleia#adding-a-formatter) through to step 6. Supply any of the `prettier` formatters using `npx`

e.g.

```bash
apheleia@c881519174c5:/src$ make fmt-test FORMATTERS=prettier-ruby
Source file `/src/apheleia.el' newer than byte-compiled file
Symbol's value as variable is void: npx
make: *** [Makefile:97: fmt-test] Error 255
apheleia@c881519174c5:/src$
```

**Comment by raxod502** [comment]
Bleh. I think this will be fixed by https://github.com/radian-software/apheleia/pull/166

**Comment by mohkale** [comment]
Fixed now.
