### ISSUE TITLE
How to prevent constant safe-local-variables prompts?

### ISSUE THREAD

**Issue by mohkale** [radian-software/apheleia#180]
Hi @raxod502 

I've encountered this in a bunch of your projects, looks like you've set a directory-local variable for compile-command to something specific for the project. Is there a way to suppress the repeated prompts for it? Every time I try to do something with magit it blocks and makes me have to enter yes to accept the variable like 5-6 times. Since it's marked unsafe I can't suppress it permanently with `!`. Do you know of a workaround? I have to imagine this isn't something you deal with day-to-day so their must be a way to silence it? :thinking:.

**Comment by raxod502** [comment]
Oopsie, sorry about that. I do indeed not see that prompt. In my copy of Emacs, this is registered by `compile.el` for the `compile-command` buffer-local variable:

```
safe-local-variable
  (closure
   (t)
   (a)
   (and
    (stringp a)
    (or
     (not
      (boundp 'compilation-read-command))
     compilation-read-command)))
```

So perhaps either:
* You have `compilation-read-command` set to nil, meaning no confirmation for running compile, and hence it's considered risky?
* We're running different versions of Emacs and the behavior has changed at some point? I'm on release 28.1 built from source.

Generally though, you should be able always set specific safe values for non-safe variables. It's configured by an alist called `safe-local-variable-values`.

**Comment by mohkale** [comment]
Thanks raxod502. You're right, I do have `compilation-read-command` set to nil. I never noticed before, it's likely something I adopted from spacemacs or another configuration years ago :upside_down_face:. Now I know why I can workaround it :smiley:.
