### ISSUE TITLE
Use-package config no longer works after formatter separation

### ISSUE THREAD

**Issue by sunng87** [radian-software/apheleia#181]
I used to configure apheleia with a  `use-package` section:

```elisp
(use-package apheleia
  :ensure t
  :config
  (setf (alist-get 'rustfmt apheleia-formatters)
        '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout"))
  :hook (prog-mode . apheleia-mode))

```

This works until recent refactoring in #161 . The `:config` clause no longer effects. If I eval the `setf` expression after emacs started,  it works. Not sure if it's a bug but I'm curious about how to configure apheleia after the refactoring..

**Comment by alternateved** [comment]
Would that work for you?

```elisp
(use-package apheleia
  :ensure t
  :init
  (require 'apheleia-formatters)
  (setf (alist-get 'rustfmt apheleia-formatters)
        '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout"))
  :hook (prog-mode . apheleia-mode))
```

This is what I went with after that update.

**Comment by sunng87** [comment]
As @alternateved pointed out, we have to require apheleia-formatters in before customizing them. 

It turns out the config clause is not evaluated during init. apheleia, at least apheleia-formatters, doesn't seems to load before I open the first `prog-mode`. I get error `(void-variable apheleia-formatters)` when manually eval the `setf` expression. And I believe it's loaded before upgrade because it doesn't require any manual process before.

**Comment by mohkale** [comment]
Well that's surprising an unexpected. To be clear you shouldn't need hacks like what @alternateved shared to work around this. Loading apheleia should load apheleia-formatters and everything else. I can't seem to reproduce the issue using straight instead of the builtin :ensure.

```elisp
(use-package apheleia
  :straight t
  :config
  (setf (alist-get 'rustfmt apheleia-formatters)
        '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout"))
  :hook (prog-mode . apheleia-mode))
```

Could someone experiencing the issue help diagnose it. To begin a backtrace of the error from setf and the specific apheleia version (git hash ideally) would be appreciated.

**Comment by mohkale** [comment]
Hmm... I'm not getting an error even from `emacs -q` when running:

```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
;; and `package-pinned-packages`. Most users will not need or want to do this.
;;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)

(use-package apheleia
  :ensure t
  :config
  (setf (alist-get 'rustfmt apheleia-formatters)
        '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout"))
  :hook (prog-mode . apheleia-mode))

(require 'apheleia)
```

and the rustfmt formatter is setup correctly :thinking:.

**Comment by mohkale** [comment]
@alternateved 

Thanks. Too quick for me :rofl:. While in the debugger can you tell me what each of the following evaluate to?

```elisp
(featurep 'apheleia)
(featurep 'apheleia-core)
(featurep 'apheleia-formatters)
```

**Comment by alternateved** [comment]
I get the same error when I evaluate first this snippet:
```lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
;; and `package-pinned-packages`. Most users will not need or want to do this.
;;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)
```

Then this snippet:
```lisp
(use-package apheleia
  :ensure t
  :config
  (setf (alist-get 'rustfmt apheleia-formatters)
        '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout"))
  :hook (prog-mode . apheleia-mode))
  ```

And then specifically this snippet:
```lisp
  (setf (alist-get 'rustfmt apheleia-formatters)
        '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout"))
```

After that this error appears.

**Comment by mohkale** [comment]
So it's reproducible. Good. Could you check [this](https://github.com/radian-software/apheleia/issues/181#issuecomment-1490756388) please.

**Comment by alternateved** [comment]
`(featurep 'apheleia)` -> `nil`
`(featurep 'apheleia-core)` -> `nil`
`(featurep 'apheleia)` -> `nil`

I did not evaluated `(require 'apheleia)` but I did run `M-x apheleia-mode` while in `emacs -Q` while running above commands.

**Comment by mohkale** [comment]
So apheliea isn't loaded or hasn't finished loading when you reach the error. While in the use-package declaration can you go to the end and run `M-x pp-macroexpand-last-sexp` and show what it outputs?

**Comment by alternateved** [comment]
Sure, here:

```elisp
(progn
  (use-package-ensure-elpa 'apheleia
			   '(t)
			   'nil)
  (defvar use-package--warning1
    #'(lambda
	(keyword err)
	(let
	    ((msg
	      (format "%s/%s: %s" 'apheleia keyword
		      (error-message-string err))))
	  (display-warning 'use-package msg :error))))
  (condition-case-unless-debug err
      (progn
	(unless
	    (fboundp 'apheleia-mode)
	  (autoload #'apheleia-mode "apheleia" nil t))
	(eval-after-load 'apheleia
	  '(condition-case-unless-debug err
	       (progn
		 (setf
		  (alist-get 'rustfmt apheleia-formatters)
		  '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout"))
		 t)
	     (error
	      (funcall use-package--warning1 :config err))))
	(add-hook 'prog-mode-hook #'apheleia-mode))
    (error
     (funcall use-package--warning1 :catch err))))
```

**Comment by alternateved** [comment]
I just want to mention that when I explicitly evaluate `(require 'apheleia)` after use-package declaration I do not get an error. But as far as I can understand, use-package declaration should load apheleia, right?

**Comment by mohkale** [comment]
I don't get it :/. It won't run the setf until after the load but the error you're describing is as if it's happening prior to loading. 

> But as far as I can understand, use-package declaration should load apheleia, right?

No. use-package defers by default. It'll only load if you set :demand t, otherwise it installs and waits for something to call an apheliea autoload and then it'll load.

**Comment by mohkale** [comment]
I'm not sure how to properly fix this. So far there's 2 people who have reported issues but I can't reproduce the problem at all :confused:. If someone could share a reproduce-able example using `emacs -q` then please do so.

**Comment by mohkale** [comment]
Also @alternateved the backtrace you shared before has you evaluating the snippet directly. If you could share one with the error triggerring on the entire use-package block then that would be more helpful.

**Comment by alternateved** [comment]
There is no error for the entire use-package block. Things within `:config` block doesn't get evaluated. So there is no error, but also configuration within this block does nothing.

If I change from `:config` to `:init` like so:
```elisp
(use-package apheleia
  :ensure t
  :init
  (setf (alist-get 'rustfmt apheleia-formatters)
        '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout"))
  :hook (prog-mode . apheleia-mode))
```

Then I will get below error trace:
```elisp
Debugger entered--Lisp error: (void-variable apheleia-formatters)
  (assq 'rustfmt apheleia-formatters)
  (if (and nil (not (eq nil 'eq))) (assoc 'rustfmt apheleia-formatters nil) (assq 'rustfmt apheleia-formatters))
  (let* ((p (if (and nil (not (eq nil 'eq))) (assoc 'rustfmt apheleia-formatters nil) (assq 'rustfmt apheleia-formatters)))) (progn (if p (setcdr p '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout")) (setq apheleia-formatters (cons (setq p (cons 'rustfmt '...)) apheleia-formatters))) '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout")))
  (condition-case err (let* ((p (if (and nil (not (eq nil ...))) (assoc 'rustfmt apheleia-formatters nil) (assq 'rustfmt apheleia-formatters)))) (progn (if p (setcdr p '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout")) (setq apheleia-formatters (cons (setq p (cons ... ...)) apheleia-formatters))) '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout"))) ((debug error) (funcall use-package--warning1 :init err)))
  (progn (if (fboundp 'apheleia-mode) nil (autoload #'apheleia-mode "apheleia" nil t)) (condition-case err (let* ((p (if (and nil (not ...)) (assoc 'rustfmt apheleia-formatters nil) (assq 'rustfmt apheleia-formatters)))) (progn (if p (setcdr p '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout")) (setq apheleia-formatters (cons (setq p ...) apheleia-formatters))) '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout"))) ((debug error) (funcall use-package--warning1 :init err))) (add-hook 'prog-mode-hook #'apheleia-mode))
  (condition-case err (progn (if (fboundp 'apheleia-mode) nil (autoload #'apheleia-mode "apheleia" nil t)) (condition-case err (let* ((p (if (and nil ...) (assoc ... apheleia-formatters nil) (assq ... apheleia-formatters)))) (progn (if p (setcdr p '...) (setq apheleia-formatters (cons ... apheleia-formatters))) '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout"))) ((debug error) (funcall use-package--warning1 :init err))) (add-hook 'prog-mode-hook #'apheleia-mode)) ((debug error) (funcall use-package--warning1 :catch err)))
  (progn (use-package-ensure-elpa 'apheleia '(t) 'nil) (defvar use-package--warning1 #'(lambda (keyword err) (let ((msg (format "%s/%s: %s" ... keyword ...))) (display-warning 'use-package msg :error)))) (condition-case err (progn (if (fboundp 'apheleia-mode) nil (autoload #'apheleia-mode "apheleia" nil t)) (condition-case err (let* ((p (if ... ... ...))) (progn (if p (setcdr p ...) (setq apheleia-formatters ...)) '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout"))) ((debug error) (funcall use-package--warning1 :init err))) (add-hook 'prog-mode-hook #'apheleia-mode)) ((debug error) (funcall use-package--warning1 :catch err))))
  (progn (progn (use-package-ensure-elpa 'apheleia '(t) 'nil) (defvar use-package--warning1 #'(lambda (keyword err) (let ((msg ...)) (display-warning 'use-package msg :error)))) (condition-case err (progn (if (fboundp 'apheleia-mode) nil (autoload #'apheleia-mode "apheleia" nil t)) (condition-case err (let* ((p ...)) (progn (if p ... ...) '...)) ((debug error) (funcall use-package--warning1 :init err))) (add-hook 'prog-mode-hook #'apheleia-mode)) ((debug error) (funcall use-package--warning1 :catch err)))))
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  command-execute(eval-last-sexp)
```

Not sure if this is helpful.

**Comment by mohkale** [comment]
@alternateved That's expected. :init runs before apheleia is loaded and so the variable is expected not to be defined. Could you try running the original use-package snippet and then evaluate `(require 'apheleia)`. The latter should not show a backtrace but if it does then we can investigate why.

**Comment by alternateved** [comment]
@mohkale running this:
```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
;; and `package-pinned-packages`. Most users will not need or want to do this.
;;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)

(use-package apheleia
  :ensure t
  :config
  (setf (alist-get 'rustfmt apheleia-formatters)
        '("rustfmt" "--quiet" "--edition" "2021" "--emit" "stdout"))
  :hook (prog-mode . apheleia-mode))

(require 'apheleia)
```

Evaluates successfully. No errors.

**Comment by raxod502** [comment]
I also am unable to reproduce any error or unexpected behavior with these sample init-files. Maybe it is possible to narrow down environment issues by preparing a recipe that works with https://github.com/Silex/docker-emacs?

**Comment by alternateved** [comment]
I've created a small file named `apheleia-debug.el` with below content:
```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(use-package apheleia
  :ensure t
  :init (apheleia-global-mode)
  :config
  (setf (alist-get 'emacs-lisp-mode apheleia-mode-alist) '(lisp-indent)))
```

And this works correctly. When I open Emacs with `emacs -q --load apheleia-debug.el` comman, open `apheleia-debug.el` and change some line - it gets indented correctly by apheleia.

But when instead of running `apheleia-global-mode` on init, I run file with below content and repeat same steps:
```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(use-package apheleia
  :ensure t
  :hook (emacs-lisp-mode . apheleia-mode)  
  :config
  (setf (alist-get 'emacs-lisp-mode apheleia-mode-alist) '(lisp-indent)))
```

Even though `apheleia-mode` gets activated, configurations are not applied (no formatting happens for `emacs-lisp-mode`. I think this is what OP had an issue with.

**Comment by alternateved** [comment]
My issue is that (I use `use-package-always-defer t`) I have to `demand` apheleia now even though I run `apheleia-global-mode` on init otherwise things in `config` block won't get applied. This wasn't the case before the https://github.com/radian-software/apheleia/pull/161 change:
```elisp
(use-package apheleia
  :demand
  :init (apheleia-global-mode)
  :config
  ;; Set custom formatting commands
  (dolist (formatter-cmd '((shfmt     . ("shfmt" "-i" "4" "-ci" "-kp" "-sr"))
                           (zigfmt    . ("zig" "fmt" (or (buffer-file-name) (buffer-name))))
                           (fourmolu  . ("fourmolu" "--indentation" "2" "--stdin-input-file"
                                         (or (buffer-file-name) (buffer-name))))))
    (add-to-list #'apheleia-formatters formatter-cmd))

  ;; Set custom formatters for modes
  (dolist (formatter-mode '((emacs-lisp-mode . lisp-indent)
                            (clojure-mode    . lisp-indent)
                            (zig-mode        . zigfmt)
                            (haskell-mode    . fourmolu)))
    (add-to-list #'apheleia-mode-alist formatter-mode)))
```

Is it expected behavior? I can live with that though. Package is excellent.

**Comment by mohkale** [comment]
@alternateved 

Just to confirm is apheleia actually active in whatever buffer you're planning to use it with in the latter case? The crux of the issue from [your previous comment](https://github.com/radian-software/apheleia/issues/181#issuecomment-1500008758) is configuration updates are only valid after apheleia has been loaded. Simply hooking apheleia into emacs-lisp-mode isn't enough to have it loaded, you must then open a file/buffer in that mode and then it'll be loaded. This is the same before and after the commit this issue is describing as the fault so I believe it's unrelated and just a misunderstanding on you or OPs part about how hooks and deferred loading work.

Before proceeding please confirm `M-x describe-mode` in the buffer where formatting is not happening shows apheleia is present. If it doesn't, then that buffer must've been created before the hook update in your use-package config and it won't have apheleia enabled. You must revert the buffer in this case.

**Comment by terlar** [comment]
I also ran into this issue (I'm also using always-defer) and fixed it by explicitly defining an `eval-after-load` for `apheleia-formatters`. The use-package `:config` section will setup `eval-after-load 'apheleia` which doesn't work with this code as it doesn't necessary load.

This is my working example:
```elisp
(use-package apheleia
  :ensure t
  :hook
  (prog-mode-hook . apheleia-mode)
  :init
  (put 'apheleia-formatter 'safe-local-variable 'symbolp)
  (eval-after-load 'apheleia-formatters
    '(progn
       (dolist (formatter '((eslint . (npx "eslint_d" "--fix-to-stdout" "--stdin" "--stdin-filename" file))
                            (nix . ("nix" "fmt" "--" "-"))
                            (rufo . ("rufo" "--simple-exit"))))
         (cl-pushnew formatter apheleia-formatters :test #'equal))
       (dolist (mode-formatter '((nix-mode . nix)
                                 (ruby-mode . rufo)))
         (cl-pushnew mode-formatter apheleia-mode-alist :test #'equal)))))
```

**Comment by mohkale** [comment]
@terlar 

As mentioned above, this shouldn't be necessary. Could you please clarify what you mean by doesn't work and ideally share a reproducible example in emacs -q?

**Comment by terlar** [comment]
By not work, I mean that it doesn't evaluate the FORM of `eval-after-load`. If I manually do `(require 'apheleia)` it will trigger the content of `:config` section of `use-package` definition.

I'll look into creating a simple reproducible `emacs -q` recipe.

With the `:defer t` switch to use-package, it will use the autoload functionality and friends, and I guess the file `apheleia` doesn't get loaded? Although the other files are loaded so you get all the functionality except the defgroup in the main file.

If I play around with this:
| `(featurep 'apheleia)` | `(featurep 'apheleia-core)` | `(featurep 'apheleia-formatters)` |
|------------------------|-----------------------------|-----------------------------------|
| ... Start Emacs ...                                                                      |
| `nil` | `nil` | `nil` |
| ... Open buffer with hook enabling `apheleia-mode` ...
| `nil` | `nil` | `nil` |
| M-x `apheleia-format-buffer` or `C-x C-s`
| `nil` | `t` | `t` |

**Comment by mohkale** [comment]
@terlar 

Thank you for the very thorough investigation.

> By not work, I mean that it doesn't evaluate the FORM of eval-after-load. If I manually do (require 'apheleia) it will trigger the content of :config section of use-package definition.

I'm still not following, that's how eval-after-load is suppposed to work. The body is not evaluated until **after** the feature you specify is provided. Manually requiring apheleia will evaluate it, enabling apheleia-mode (and then modifying and saving a buffer) or calling `apheleia-format-buffer` will also evaluate it. Why do you want it to be evaluated early? Or am I misreading what you meant?

**Comment by mohkale** [comment]
Ah, actually I see you've got featurep apheleia is nil when `apheleia-format-buffer` is called directly. That's surprising. Investigating.

**Comment by mohkale** [comment]
Ah, yep, I see what happened here. We moved the definition of those interactive functions to apheleia-core.el so now it's loaded instead of apheleia.el when their called. If you use deferred loading and the major-mode or interactive function for formatting then the regular apheleia file is never autoloaded so it's feature is never provided.

**Comment by mohkale** [comment]
@terlar 

When you get a chance could you try the changes from #185 PR? I believe they should fix this issue for you. Once I get confirmation I'll approve and merge it in myself to avoid anyone else running into this issue.

Also apologies @alternateved and @sunng87 for taking so long to understand what the issue was :sweat_smile:. The linked PR will also sadly break the hacks you've put in place for with-eval-after-load apheleia-formatters but hopefully you can easily revert to the configuration you had before.

**Comment by alternateved** [comment]
No worries. Unfortunately I wasn't able to clearly explain where the issue was. Thanks @terlar for help here!

@mohkale Your PR works for me. There is no need to additionally require apheleia anymore, enabling apheleia-mode or apheleia-global-mode is enough and configuration is properly read.

Example of my (working now) configuration:
```elisp

(use-package apheleia
  :defer t
  :bind ("C-c t a" . apheleia-mode)
  :init (apheleia-global-mode)
  :config
  ;; Set custom formatting commands
  (dolist (formatter-cmd '((shfmt     . ("shfmt" "-i" "4" "-ci" "-kp" "-sr"))
                           (zigfmt    . ("zig" "fmt" (or (buffer-file-name) (buffer-name))))
                           (fourmolu  . ("fourmolu" "--indentation" "2" "--stdin-input-file"
                                         (or (buffer-file-name) (buffer-name))))))
    (add-to-list #'apheleia-formatters formatter-cmd))

  ;; Set custom formatters for modes
  (dolist (formatter-mode '((emacs-lisp-mode . lisp-indent)
                            (clojure-mode    . lisp-indent)
                            (zig-mode        . zigfmt)
                            (haskell-mode    . fourmolu)))
    (add-to-list #'apheleia-mode-alist formatter-mode)))
```

**Comment by terlar** [comment]
Thank you for the quick turn-around. I can confirm it works for me as well, reverted my workaround and updated the package.

**Comment by sunng87** [comment]
Thank you @mohkale I confirm the new version works as well. It's much straight-forward now.

**Comment by alternateved** [comment]
Hello. I did not test it well enough yet, but after latest commit I get below error:
```lisp
Debugger entered--Lisp error: (void-variable file)
  eval(file)
  apheleia--formatter-context(prettier-typescript (npx "prettier" "--stdin-filepath" filepath "--parser=typescript" (apheleia-formatters-js-indent "--use-tabs" "--tab-width")) nil nil)
  apheleia--run-formatter-process((npx "prettier" "--stdin-filepath" filepath "--parser=typescript" (apheleia-formatters-js-indent "--use-tabs" "--tab-width")) #<buffer SomeTsFile.ts> nil #f(compiled-function (stdout) #<bytecode 0x1a809af184805f5>) nil prettier-typescript)
  apheleia--run-formatters((prettier-typescript) #<buffer SomeTsFile.ts> nil #f(compiled-function (formatted-buffer) #<bytecode -0x1840ef4db241010f>))
  apheleia-format-buffer((prettier-typescript) #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_17>)
  apheleia--format-after-save()
  run-hooks(after-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  command-execute(save-buffer)
  ```
