### ISSUE TITLE
Add example of how to set apheleia-formatter value in .dir-locals.el to README.md

### ISSUE THREAD

**Issue by kaliif** [radian-software/apheleia#190]
I need to specify different set of formatters for some projects (specifically (isort black) for python mode). The current documentation suggests that this is possible but (probably due to my lack of emacs-lisp) I have not been able to figure this out. Would be great to have an example or two.

**Comment by raxod502** [comment]
Does

```
((python-mode . ((apheleia-formatter . (isort black)))))
```

work?

Also, see https://github.com/radian-software/apheleia/commit/01f2f0da561e29b75c6b12933943a40850cf704c

**Comment by Eason0210** [comment]
> Does
> 
> ```
> ((python-mode . ((apheleia-formatter . (isort black)))))
> ```
> 
> work?
It works on macOS  and Windows with Emacs 30, Thanks.
