### ISSUE TITLE
prettier-javascript not working properly on emacs 30

### ISSUE THREAD

**Issue by yassernasc** [radian-software/apheleia#192]
Although configurations, tabs is used instead space after formatting, quite long tabs.. equivalent to 8 spaces.

Trying **editorconfig**, `indent_style` and `indent_size` properties are ignored.
At **prettier config**, tabWidth by default is 2 and useTabs by default is false and still settings those manually are both ignored.

I suspected that the indentation implementation from new tree-sitter modes like `js-ts-mode` could overwrite prettier's; but the issue persists with `js-mode`.

Can't imagine the reason of that behavior.

---
Emacs version: GNU Emacs 30.0.50
OS: macOS Monterey

**Comment by yassernasc** [comment]
I understand that probably isn't a issue with apheleia, what I need is more is some help to understand what might be the problem. And if this occasionally happen with other people. :)

**Comment by raxod502** [comment]
Sorry, I'm having a bit of trouble understanding. You're saying that your JavaScript code is being formatted with tabs although you would expect it to be formatted with spaces?

Do you have `indent-tabs-mode` set to non-nil (which instructs Emacs to indent with tabs)?

**Comment by yassernasc** [comment]
you understood perfectly, sorry about that.

and yes, that's it, I just added this two section at my .emacs file and now everything is in place:
```elisp
(set-default 'indent-tabs-mode nil) 
```

```elisp
(use-package js
  :ensure nil
  :custom
  (js-indent-level 2))
```

I suppose expecting those variables overwriting based on prettier's config is asking too much, I am okay with this solution, thanks friend.

**Comment by raxod502** [comment]
It's a fair complaint that this is unintuitive. Apheleia previously delegated exclusively to Prettier. But I think it is much more reasonable to use the user's already configured indentation settings in Emacs. In my opinion, the problem is that Emacs defaults to `indent-tabs-mode` non-nil, which is never what anybody wants.
