### ISSUE TITLE
variable apheleia-formatter is not buffer-local by default

### ISSUE THREAD

**Issue by edslocomb** [radian-software/apheleia#199]
In order to avoid having `apheleia-formatter` applied to new buffers, I found I had to use:
```elisp
(set (make-local-variable 'apheleia-formatter) 'my-preferred-formatter))
```

in my init.el, rather than `setq`.  The [emacs `wiki](https://www.emacswiki.org/emacs/BufferLocalVariable)` seems to suggest that this can be remedied by adding 
```elisp
(make-variable-buffer-local 'apheleia-formatter)
```

to apheleia's source somewhere.

**Comment by raxod502** [comment]
The variable is defined as a local variable like so:

```elisp
(defvar-local apheleia-formatter nil
  "Name of formatter to use in current buffer, a symbol or nil.
If non-nil, then `apheleia-formatters' should have a matching
entry. This overrides `apheleia-mode-alist'.

The value can also be a list of symbols to apply multiple
formatters in sequence.")
```

Are you setting it before loading Apheleia? I am not sure why your Emacs would not treat this as a local variable.

**Comment by edslocomb** [comment]
Whatever it is in my config, the code I used above works for me.  I'll close the ticket, if anyone else has a similar problem then hopefully they'll be able to find this and fix it.

**Comment by edslocomb** [comment]
Whatever it is in my config, the code I used above works for me. I'll close the ticket, if anyone else has a similar problem then hopefully they'll be able to find this and fix it.

**Comment by edslocomb** [comment]
FWIW, this is the relevant bit of my init.el:

```elisp
(apheleia-global-mode +1)

(defun prefer-ruby-standard ()
  "Use ruby-standard for flycheck and apheleia when .standard.yml file is present in project root."
  (when (file-exists-p (expand-file-name ".standard.yml" (projectile-project-root)))
    ;; Remove the next line if you add ruby-standard extensions to your .rubocop.yml; see ruby-standard docs
    (add-to-list 'flycheck-disabled-checkers 'ruby-rubocop)
    (set (make-local-variable 'apheleia-formatter) 'ruby-standard)))

(add-hook 'ruby-mode-hook 'prefer-ruby-standard)
```

I was seeing `apheleia-formatter` still set to `ruby-standard` in new buffers for typescript (.ts, .tsx) files when using `(setq ...)` instead of `(set (make-local-variable ...) ...)`

**Comment by raxod502** [comment]
Oh, I see what's happening. The mode declaration is autoloaded, which means you can enable it without actually loading Apheleia, which leads to the variable not necessarily being loaded even after you enable the minor mode. Once the feature gets loaded, the variable is made buffer local, but by then it is too late because your `setq` has already adjusted the default. Going to autoload the variable as well to avoid this.
