### ISSUE TITLE
difference in formatting yaml between prettier and apheleia 

### ISSUE THREAD

**Issue by darosio** [radian-software/apheleia#202]
This is the difference between the auto-formatted by apheleia in a ci.yml file

   checks:
    name: Mypy and xdoctest ${{ matrix.python }} on ${{ startsWith(matrix.os,

vs. prettier

   checks:
    name:
      Mypy and xdoctest ${{ matrix.python }} on ${{ startsWith(matrix.os,

I do not understand why this is occurring. Any idea?

**Comment by raxod502** [comment]
Are you working within an NPM project? If so, by default Apheleia would use the Prettier version used in your project, which might be different from the one you are running manually.

**Comment by darosio** [comment]
No actually I am working in a python project and the difference I was complaining about it was due the the [--prose-wrap=always] set in the pre-commit-config.yaml. Both pre-commit and apheleia are using prettier v3.0.0 but only one with the extra parameter. Sorry for my oversight.
Thank you Radon for pointing me to the right direction.

**Comment by darosio** [comment]
No actually I am working in a python project and the difference I was complaining about it was due the the [--prose-wrap=always] set in the pre-commit-config.yaml. Both pre-commit and apheleia are using prettier v3.0.0 but only one with the extra parameter. Sorry for my oversight.
Thank you Radon for pointing me to the right direction.
– daniele

**Comment by raxod502** [comment]
No problem! Glad to help.
