### ISSUE TITLE
SCSS is used wrong parser

### ISSUE THREAD

**Issue by cxa** [radian-software/apheleia#206]
I've encountered an issue with the formatter order in `apheleia-formatters`, resulting in `prettier-css` being used for SCSS files instead of `prettier-scss` because of https://github.com/radian-software/apheleia/blob/937fe9a940451cb00afc769bef8bbd7e3b281f86/apheleia-core.el#L1037C35-L1037C41. (since `scss-mode` is derived from `css-mode`).

My temporary workaround:

```elisp
(push '(scss-mode . prettier-scss) apheleia-mode-alist)
```

It effectively specifies the correct formatter for SCSS files until the underlying issue is resolved.

**Comment by raxod502** [comment]
This has occurred a few times. I will fix the problem so it is not necessary to specify modes in a careful order. See https://github.com/radian-software/apheleia/pull/207.
