### ISSUE TITLE
Misc fixes

### ISSUE THREAD

**Issue by mohkale** [radian-software/apheleia#212]
Opening to remind myself to prioritise this:

1. If a formatter is installed on a remote but not locally apheleia will skip formatting.
2. jq formatter currently colorizes the output by default for me.
3. clang-format uses buffer-file-name which doesn't respect remote file paths.

**Comment by mohkale** [comment]
Also, in general, I find tracing through apheleia code a little hard (given I wrote a lot of it that's not good :sweat_smile:). We should refactoring it a little here and their. Maybe decoupling the formatter running from the patch application to support plugging it into a library for example.

**Comment by raxod502** [comment]
The structure isn't great, I agree. Most of that is my fault and I agree things need to change. I've got some work in progress for making it more testable (https://github.com/radian-software/apheleia/pull/204), and other refactoring is needed, as well.
