### ISSUE TITLE
replace haskell formatter?

### ISSUE THREAD

**Issue by edslocomb** [radian-software/apheleia#219]
Apheleia's default haskell formatter, [brittany](https://github.com/lspitzner/brittany/), is no longer maintained as of a bit under a year ago.

I learned this while trying to run a full `make fmt-docker`, which failed on the brittany test; I was unable to get the installer working and it looks like even brittany's author has [had issues](https://github.com/lspitzner/brittany/#installation) with installation.

I'd propose removing brittany from apheleia and replacing it with another haskell formatter.   A brief bit of looking around turned up [hindent](https://github.com/mihaimaruseac/hindent) and [ormolu](https://github.com/tweag/ormolu).

I'll have a go at adding formatters for those, but I'm not a haskell dev and don't have an opinion about which should be the new default.

Any input appreciated?

**Comment by zzantares** [comment]
Please consider setting either [`fourmolu`](https://github.com/fourmolu/fourmolu) or [`ourmolu`](https://github.com/tweag/ormolu) as the default Haskell formatter, I'd say these are the most widely used ones for industrial Haskell code today.

**Comment by raxod502** [comment]
https://github.com/radian-software/apheleia/pull/221, merged, adds those two formatters. https://github.com/radian-software/apheleia/pull/222 fixes the brittany installation (it was just a matter of the ubuntu version being too old, though I agree with the brittany author that haskell package installation is a mess). I'd like to wait at least a little time after the new formatters are added to Apheleia (say, 3 months?) before switching to make one of them the default though. Just to give people a chance to try them out before swapping it for everyone.
