### ISSUE TITLE
Add support for `ruff format` for Python files

### ISSUE THREAD

**Issue by offbyone** [radian-software/apheleia#233]
The `ruff` linter has gained formatter support: https://github.com/astral-sh/ruff#usage

It's in beta, but it's mostly black-compatible, but much faster. I'd love it if Python formatting could use the "right" formatter depending on if `black` or `ruff` are installed. 

I'm happy to submit a PR for this support.

**Comment by raxod502** [comment]
Sure, that sounds fine to me. Let's keep `black` as the default for now, but add support for `ruff` so that users can set it to be used for Python if they prefer.

**Comment by offbyone** [comment]
I have opened a PR for this; I'm happy to add any changes you see fit, but it's at least passing checks :D
