### ISSUE TITLE
Apheleia does not format with formatters installed with npm

### ISSUE THREAD

**Issue by alternateved** [radian-software/apheleia#241]
Hello!

After changes introduced in 54a192c3454e82be9d5ad910d80796b27d58035f formatters installed globally with npm do not work. I briefly tested those installed locally but they also do not seem to work anymore. Other formatters seems fine.

**Comment by dschrempf** [comment]
I debugged `apheleia--run-formatter-process` and it seems that line 935
```
      (when (executable-find (apheleia-formatter--arg1 ctx)
```
does not find `apheleia-npx`. I only find the lisp code of apheleia on my system but not the script. I wonder if this is a problem on my side (script is not bundled) or here.

**Comment by edslocomb** [comment]
hmph, all of the non-elisp files are missing...

**Comment by edslocomb** [comment]
I've put a PR in to melpa to include the missing scripts in the recipe:

https://github.com/melpa/melpa/pull/8809

**Comment by edslocomb** [comment]
...and while we wait for the gears to turn, you can clone apheleia locally and point to it in your init.el with:

```elisp
(use-package apheleia :load-path "~/[your path to]/apheleia/")
```

**Comment by alternateved** [comment]
Or run `M-x package-vc-install RET "https://github.com/radian-software/apheleia"` (if Emacs 29) and then: 
```elisp
(use-package apheleia :ensure nil)
```

**Comment by raxod502** [comment]
This is definitely an error on my part and should be fixed, but it's also worth noting that `straight.el` users will not run into the problem, cf https://github.com/melpa/melpa/pull/8809#issuecomment-1806961223.

**Comment by alternateved** [comment]
This issue is no more thanks to fix in https://github.com/melpa/melpa/pull/8809. Thanks for help @edslocomb and @raxod502!
