### ISSUE TITLE
Not picking up prettier installed via yarn pnp properly when using melpa package

### ISSUE THREAD

**Issue by edslocomb** [radian-software/apheleia#244]
I'm seeing a weird thing where the pnp install isn't picked up if I start emacs in the project root, but it works if I start emacs one directory closer to the file being edited.

afaict this is due to the apheleia-npx script not knowing where the file to be formatted is (buffer contents are piped to it so apheleia can work when there's no filename associated with the buffer)

I'm thinking the thing to do here is rewrite apheleia-npx as an elisp function; I'll tinker a bit and put a PR in if it works well

**Comment by edslocomb** [comment]
OK now I can't repo the behavior, closing.

**Comment by raxod502** [comment]
The filename shouldn't matter, as `apheleia-npx` works based on working directory, which should always be set.
