### ISSUE TITLE
ormolu backend for haskell-mode is broken

### ISSUE THREAD

**Issue by Eason0210** [radian-software/apheleia#312]
Hi,

Because the default[ brittany](https://github.com/lspitzner/brittany/?tab=readme-ov-file#brittany---) for haskell-mode is unmaintained, and the repos recommand  to use **ormolu** instead.

But the `ormolu` (version: ormolu 0.7.7.0) don't works with cabal project, will get below error message in **\*aphelia-ormolu-log\*** buffer:

```
$ ormolu

The --stdin-input-file option is necessary when using input
from stdin and accounting for .cabal files

Command failed with exit code 9.
```

my configs:

```emcs-lisp
(setf (alist-get 'haskell-mode apheleia-mode-alist) 'ormolu)
```

with below config, will fix the issue.

```emacs-lisp
(push '(ormolu . ("ormolu"
                    `("--stdin-input-file" ,buffer-file-name)))
        apheleia-formatters)
```

Expected this can be fixed in apheleia. 

Maybe it is time to change the default backend for haskell-mode to ormolu instead of brittany?

**Comment by raxod502** [comment]
Fair enough. If the maintainer of the original formatter recommends switching, then it seems logical for us to switch as well, to encourage best practices as determined by each language's community.

Let me see if I can add a test case that will prevent a regression like this, too... I've done some work on more robust formatter tests that can leverage an entire project directory.

**Comment by raxod502** [comment]
Nevermind, no new tests needed, we just need to run the existing ones again from time to time. That might be a good idea, run the full formatter test suite on a monthly schedule or something and have a bot file an issue for ones that are failing.

![image](https://github.com/user-attachments/assets/65ffe683-7505-47d1-bc24-bb4b1db542ae)
