### ISSUE TITLE
How can I set 4 space indent for yaml files?

### ISSUE THREAD

**Issue by avatar-lavventura** [radian-software/apheleia#84]
When `apheleia-format-buffer` applied in a `yaml` file it converts 4 space indents into 2 spaces indent.

How can I set 4 space indent for the yaml file?

**Comment by raxod502** [comment]
You can create a Prettier configuration file as documented [here](https://prettier.io/docs/en/configuration.html), and set the [tab width](https://prettier.io/docs/en/options.html#tab-width) configuration option in it. You can also do this via `.editorconfig`. Alternatively, you can modify the `prettier` entry in the `apheleia-formatters` alist to pass the `--tab-width` option.

**Comment by avatar-lavventura** [comment]
Can I use latexindent (https://github.com/cmhughes/latexindent.pl) instead of `prettier`?
Is there any global `.editorconfig` file or should I create in in all the repos that emacs file is opened?

**Comment by raxod502** [comment]
Sure, you can configure `apheleia-formatters` and `apheleia-mode-alist` however you like to enable a different formatter for your favorite modes. That said, weren't you trying to indent YAML files? Is latexindent suitable for that?

For questions about EditorConfig, please see the upstream documentation; e.g. [this answer](https://github.com/sindresorhus/atom-editorconfig/issues/14#issuecomment-51644161).

For modifying alists in Emacs, there are good external resources; see [e.g. this answer](https://emacs.stackexchange.com/a/32871).

**Comment by avatar-lavventura** [comment]
Yes sir  `latexindent` is suitable for that, by having `defaultIndent: "    "` line on `localSettings.yaml` where it applied this format.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/radian-software/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)

**Comment by avatar-lavventura** [comment]
@raxod502 I believe I responded to questions, what additional information should I provide? Thanks in advance.

**Comment by raxod502** [comment]
I apologize for this, I was offline for a long time and I should have disabled the bot during that time. My bad.

**Comment by raxod502** [comment]
That said, I also think I responded to your questions in https://github.com/radian-software/apheleia/issues/84#issuecomment-1100935264, what were you looking for further guidance on?
