### ISSUE TITLE
How can I make isort under apheleia works same as isort under pre-commit?

### ISSUE THREAD

**Issue by avatar-lavventura** [radian-software/apheleia#92]
My default `isort` setup in the `setup.cfg` file is:

```bash
[tool:isort]
force_grid_wrap = 0
include_trailing_comma = True
known_standard_library = tkinter
line_length = 120
multi_line_output = 3
use_parentheses = True
```

This applied on the pre-commit. But I realize that isort runs inside `apheleia` acts different than the isort works on the `pre-commit`.  Like isort inside emacs changes the import locations than when I run pre-commit it got changes again. Is it possible to make `isort` works parallel that works in the `pre-commit`?

**Comment by thisch** [comment]
Does isort behave the same if you run it outside emacs? If not then it is not a problem with apehlia.

**Comment by avatar-lavventura** [comment]
`isort` does not behave the same when I run it outside emacs. Hence it is a problem with aphelia.

**Comment by mohkale** [comment]
isort should function the same outside of apheleia as it does inside. If it doesn't it's likely a bug. There's one reason I can think of for why this might be happening. Apheleiea always runs the formatter in the same working directory as the buffer. git commit-hook always runs it from the root of your project. Could you try running isort outside of apheleia in the same directory as the file being formatted and confirm it's the same behaviour as the commit-hook. If this is the case please share an example python file and maybe a project layout as well.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/radian-software/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
