### ISSUE TITLE
Renaming default branch from 'master' to 'main'

### ISSUE THREAD

**Issue by raxod502** [radian-software/apheleia#99]
Following https://github.com/github/renaming, I've renamed the default branch on Apheleia from `master` to `main`. You can update your local copy following [these instructions](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch):

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

Let me know if this change causes any disruption and I can see what I can do to mitigate!

**Comment by raxod502** [comment]
Pushed https://github.com/radian-software/apheleia/commit/b25256f1b014ee02887c7882a789f95dc87d061b to fix CI errors cc/ @elken and I've updated your PR branches, sorry for the inconvenience.

**Comment by elken** [comment]
Think this is probably ok to close now?

**Comment by raxod502** [comment]
Yep, sorry for delay.
